CREATE TABLE IF NOT EXISTS department (
	id SERIAL PRIMARY KEY,
	name VARCHAR(127)
);

CREATE TABLE IF NOT EXISTS employee (
	id SERIAL PRIMARY KEY,
	name VARCHAR(127),
	department_id INTEGER REFERENCES department(id) ON DELETE SET NULL,
	boss_id INTEGER REFERENCES employee(id) ON DELETE SET NULL
);
